config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  resources :links, only: [:index, :create]

  get '/s/:slug', to: 'links#show', as: :short
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  # validations
  validates :url, presence: true, format: URI::regexp(%w[http https]), length: { within: 7..65536, on: :create, messages: "too long"}
  validates :slug, presence: true, uniqueness: true

  # associations
  belongs_to :user, optional: true

  # hooks
  before_validation :generate_slug

  # returns short url
  def short
    Rails.application.routes.url_helpers.short_url(slug: self.slug)
  end

  private
    def generate_slug
      self.slug = SecureRandom.urlsafe_base64[0..5] if self.slug.nil? || self.slug.empty?
      true
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :recoverable, :rememberable
  devise :database_authenticatable, :registerable, :validatable

  # associations
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # hooks
  before_action :authenticate_user!, only: [:index]

  def show
    @link = Link.find_by_slug(params[:slug]) 
    return redirect_to root_path, alert: "Link not found!" if @link.nil?
    @link.update_attribute(:clicks, @link.clicks + 1)
    redirect_to @link.url
  end

  def create
    links = current_user.present? ? current_user.links : Link
    @link = links.find_or_create_by(link_params)
    if @link.valid?
      redirect_to root_path, notice: @link.short
    else
      redirect_to root_path, alert: @link.errors.full_messages.join(", ")
    end
  end

  def index
    @links = current_user.links
  end

  private
    def link_params
      params.require(:link).permit(:url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @link = current_user.present? ? current_user.links.build : Link.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/shared/navbar' %>
    <main class="flex-shrink-0">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/shared/footer' %>
  </body>
</html>

app/views/layouts/shared/_alerts.html.erb
<% if notice.present? %>
  <div class="alert alert-success">
    <% if notice.include?("http") %>
      Your Shortened URL : <%= link_to notice, notice, target: "_blank" %>
    <% else %>
      <%= notice %>
    <% end %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/layouts/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
  <div class="container">
    <span class="text-muted">All Rights Reserved</span>
  </div>
</footer>

app/views/layouts/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "URL shortener", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <% if current_user %>
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Saved Links", links_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/links/index.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-md-10 mx-auto col-lg-10">
      <h1 class="display-6 fw-bold lh-1 mb-3 text-center">Saved Links</h1>
      <div id="user_links" class="p-4 p-md-5 border rounded-3 bg-light">
        <table class="table table-dark table-striped table-responsive">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Short URL</th>
              <th scope="col"># of Clicks</th>
              <th scope="col">Actual URL</th>
            </tr>
          </thead>
          <tbody>
            <% @links.each_with_index do |link, i| %>
              <tr>
                <th scope="row"><%= i + 1 %></th>
                <td><%= link.short %></td>
                <td><%= link.clicks %></td>
                <td title="<%= link.url %>"><%= link.url[0..30] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-md-10 mx-auto col-lg-10">
      <h1 class="display-6 fw-bold lh-1 mb-3 text-center">URL Shortener</h1>
      <%= render "layouts/shared/alerts" %>
      <%= form_with model: @link, class: "p-4 p-md-5 border rounded-3 bg-light" do |form| %>
        <div class="form-floating mb-3">
          <%= form.text_field :url, class: "form-control", placeholder: "http://example.com" %>
          <%= form.label :url, "Please Enter the URL:" %>
        </div>
        <%= form.submit "Shorten", class: "w-100 btn btn-lg btn-primary" %>
      <% end %>
    </div>
  </div>
</div>